### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vbauer** [adamzap/landslide#173]
I've got the following exception on Windows 7 with Python 3:

```bash
$ landslide slides.md
Traceback (most recent call last):
  File "c:\Python34\Scripts\landslide-script.py", line 9, in <module>
    load_entry_point('landslide==1.1.1', 'console_scripts', 'landslide')()
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 353, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 2302, in load_entry_point
    return ep.load()
  File "C:\Python34\lib\site-packages\pkg_resources.py", line 2029, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "C:\Python34\lib\site-packages\landslide\main.py", line 181
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

UPD: A lot of issues with Python 3 support.
UPD2: I've just fixed all issues with Python 3 locally. If you'd like I can send you pull request.

**Comment by pauljohn32** [comment]
I'm seeing that same error on Ubuntu, with python 3.4 and landslide installed with pip3 on 2015-02-27.  However, I can confirm that downloading landslide from the Git repo and re-building solves the problem. I can compile your example presentation and it looks nice.

**Comment by adamzap** [comment]
I finally cut a release!

v1.1.2 is now on PyPI
