### ISSUE TITLE
pkg_resources.DistributionNotFound: Pygments

### ISSUE THREAD

**Issue by shenyp09** [adamzap/landslide#176]
```
Traceback (most recent call last):
  File "/usr/local/bin/landslide", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: Pygments
```

**Comment by adamzap** [comment]
I'm unable to reproduce this with a fresh install on both Python 2 and 3.

Please reopen this issue if the problem persists.

Thanks!

**Comment by ztzt** [comment]
I have the same problem
mac os python 2.7
```
zhoutaodeMacBook-4:markdown zhoutao$ landslide example.md -i -o > name_you_like.html
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/landslide", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/7.2/lib/python2.7/site-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/7.2/lib/python2.7/site-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/7.2/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Pygments
```

**Comment by adamzap** [comment]
@ztzt How did you install Landslide?

**Comment by ztzt** [comment]
through pip


Pygments is already installed.


zhoutaodeMacBook-4:~ zhoutao$ sudo pip install Pygments
The directory '/Users/zhoutao/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/zhoutao/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): Pygments in /Library/Frameworks/Python.framework/Versions/7.2/lib/python2.7/site-packages


－－－－－－
亿保健康研发中心 周涛
15658883818


原始邮件
发件人:Adam Zapletalnotifications@github.com
收件人:adamzap/landslidelandslide@noreply.github.com
抄送:ztzt17180042@qq.com; Mentionmention@noreply.github.com
发送时间:2016年5月9日(周一) 11:01
主题:Re: [adamzap/landslide] pkg_resources.DistributionNotFound: Pygments(#176)


@ztzt How did you install Landslide?

**Comment by adamzap** [comment]
It seems to be a problem with your python or pip installation. Would you consider switching to homebrew and see if it works? http://docs.python-guide.org/en/latest/starting/install/osx/
