### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zhuyeqing** [adamzap/landslide#189]
Traceback (most recent call last):
  File "/usr/bin/landslide", line 9, in <module>
    load_entry_point('landslide==1.1.3', 'console_scripts', 'landslide')()
  File "/usr/lib/python2.7/site-packages/landslide/main.py", line 171, in main
    run(input_file, options)
  File "/usr/lib/python2.7/site-packages/landslide/main.py", line 162, in run
    generator.Generator(input_file, **options.__dict__).execute()
  File "/usr/lib/python2.7/site-packages/landslide/generator.py", line 206, in execute
    print(self.render().encode(self.encoding))
  File "/usr/lib/python2.7/site-packages/landslide/generator.py", line 502, in render
    context = self.get_template_vars(slides)
  File "/usr/lib/python2.7/site-packages/landslide/generator.py", line 417, in get_template_vars
    'slides': slides, 'toc': self.toc, 'embed': self.embed,
  File "/usr/lib/python2.7/site-packages/landslide/generator.py", line 194, in toc
    stack.append(stack[-1][-1]['sub'])
IndexError: list index out of range

**Comment by adamzap** [comment]
Could you post the input file that generated this error?

**Comment by adamzap** [comment]
I'll reopen this if I get more information
